config/routes.rb
Rails.application.routes.draw do
 root :to => 'links#index'
  resources :links do
    member do
      get :upvote
      patch :upvote
    end
    resources :comments
  end

  resources :comments do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, :presence => true
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable
  belongs_to :link
end

app/models/concerns/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  validates :text, :presence => true
end

app/models/link.rb
require 'date'

class Link < ActiveRecord::Base
  has_many :comments, :as => :commentable
  validates :url, :presence => true

  scope :recent, -> { order("links.rank DESC").limit(20) }

  def self.calc_rank
    Link.all.each do |link|
      days_since = DateTime.now - link.created_at.to_datetime
      if days_since < 30
        new_rank = (0.3*link.votes) + (0.7*(30-days_since))
        link.update(:rank => new_rank)
      else
        link.update(:rank => 0)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :load_commentable

def index
  @comments = @commentable.comments
end

def new
  @comment = @commentable.comments.new
end

def create
  @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = "comment added!"
      redirect_to @comment.commentable
    else
      render 'new'
    end
end

def show
  @comment = @commentable.comments.find(params[:id])
  @link = Link.find(@comment.commentable_id)
end

def edit
  @link = Link.find(params[:link_id])
  @comment = @commentable.comments.find(params[:id])
end

def update
  @comment = @commentable.comments.find(params[:id])
  @link = Link.find(@comment.commentable_id)
  if @comment.update(comment_params)
      flash[:notice] = "Comment updated"
      redirect_to link_path(@link)
    else
      flash[:alert] = "error, try again."
      render 'edit'
    end
end

def destroy
  @comment = @commentable.comments.find(params[:id])
  @comment.destroy
  flash[:notice]= "The comment has been deleted."
  redirect_to link_path(@link)
end

private
  def comment_params
    params.require(:comment).permit(:text, :commentable_type, :commentable_id)
  end

  def load_commentable
    resource = request.path.split('/')[1]
    id = request.path.split('/')[2] || params[:comment][:commentable_id]
    @commentable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.calc_rank
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      flash[:notice] = "Link added!"
      redirect_to link_path(@link)
    else
      render 'new'
    end
  end

  def show
    @link = Link.find(params[:id])
    @comment = Comment.new(commentable_type: "Link", commentable_id: @link.id)
  end

  def edit
     @link = Link.find(params[:id])
   end

  def update
    @link = Link.find(params[:id])
    if link.update(link_params)
      flash[:notice] = "Link updated"
      redirect_to link_path(@link)
    else
      flash[:alert] = "error, try again."
      render 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    flash[:notice] = "The link has been deleted."
    redirect_to links_path
  end

  def upvote
    @link = Link.find(params[:id])
    Link.increment_counter(:votes, params[:id])
    flash[:notice] = "#{@link.description} was successfully upvoted!"
    redirect_to links_path
  end

private
  def link_params
    params.require(:link).permit(:url, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li class="comment">
  <div class="body">
    <%= comment.text %>
  <%= link_to '(Reply)', new_comment_comment_path(comment) %>
  </div>
  <% unless comment.comments.empty? %>
    <ul class="comment_list">
      <%= render :partial => 'layout/comment', :collection => comment.comments %>
    </ul>
  <% end %>
</li>

app/views/comments/_comment_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for([@link, @comment]) do |f| %>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_field :text %>
  </div>

  <%= f.hidden_field :commentable_type %>
  <%= f.hidden_field :commentable_id %>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/comments/edit.html.erb
<div class="page-header">
  <h1>Edit Comment <small><%=@comment.text%></small></h1>
</div>
<%= render('comments/comment_form') %>

app/views/comments/new.html.erb
<div class="page-header">
  <h1>Hacker News <small>Comment</small></h1>
</div>

<%= render('comments/comment_form') %>

app/views/comments/show.html.erb
<div class="page-header">
  <h1>Comment Details</h1>
</div>

<div class="row">
  <div class="col-md-6">
    <div id="comment_detail">
      <p>Description: <%=@comment.text%></p>
      <p>Created <%=@comment.created_at%></p>
    </div>
    <%= link_to "Edit", edit_link_comment_path(@comment, @link), :class => "btn-small btn-primary" %>
    <%= link_to "Delete", link_comment_path(@comment, @link), :data => {:confirm => "Are you sure?", :method => "delete"}, :class => "btn-small btn-danger" %>
  </div>

<div id="comment">
  <br>
    <%=render 'comments/comment_form'%>
  </div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Hacker News</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Links", links_path %></li>
        <li><%= link_to "New link", new_link_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>
<%= flash[:notice] %>
<%= flash[:alert] %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/links/_form.html.erb
<%= render('layouts/errors', :object => @link) %>

<%= form_for(@link) do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :url %>
    <%= f.text_field :url %>

  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/links/edit.html.erb
<div class="page-header">
  <h1>Edit Link <small><%=@link.description%></small></h1>
</div>
<%= render('form') %>

app/views/links/index.html.erb
<div class="page-header">
  <h1>Hacker News <small>Top stories</small></h1>
</div>
<ul>
  <% @links.each do |link| %>
    <li><%= link_to "#{link.description}", link_path(link) %>  <%= link_to "Upvote", upvote_link_path(link), :class => "btn btn-primary" %></li>
  <% end %>
</ul>

app/views/links/new.html.erb
<div class="page-header">
  <h1>Hacker News <small>Add a link</small></h1>
</div>

<%= render('form') %>

app/views/links/show.html.erb
<div class="page-header">
  <h1>Link Details</h1>
</div>

<div class="row">
  <div class="col-md-6">
    <div id="link_detail">
      <p>Description: <%=@link.description%></p>
      <p>URL: <%=@link.url%></p>
      <p>Rank: <%=@link.rank%></p>
      <p>Votes: <%=@link.votes%></p>
    </div>
    <%= link_to "Edit", edit_link_path(@link), :class => "btn-small btn-primary" %>
    <%= link_to "Delete", link_path(@link), :data => {:confirm => "Are you sure?", :method => "delete"}, :class => "btn-small btn-danger" %>
  </div>

  <div class="col-md-6">
    <h3> Comments </h3>
      <ul>
      <% @link.comments.each do |comment| %>
        <li><%= link_to "#{comment.text}", edit_link_comment_path(@link, comment) %> </li>
      <% end %>
    </ul>
  </div>
</div>

<div id="comment">
  <br>
    <%=render 'comments/comment_form'%>
  </div>